4.0.1

diff --git a/tools/runtest b/tools/runtest
--- a/tools/runtest
+++ b/tools/runtest
@@ -19,18 +19,21 @@
 #
 # You should have received a copy of the GNU Lesser General Public
 # License along with this library; if not, write to the Free Software
-# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
+# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 #
 
 usage()
 {
     cat >&2 <<EOF
 
-Usage: $0 [options] input_file
+Usage: $0 [options] [input_file]
+
+input_file:  the source code for the test program
 
 Options:
     -q       quiet mode
     -v       verbose mode (can be specified multiple times)
+    -i       interactive mode (runs even more tests)
     -s       announce successful tests
     -p prog  name of the program to run for C tests
     -P name  set the current platform name
@@ -46,7 +49,7 @@ platform=$WINETEST_PLATFORM
 WINETEST_DEBUG=${WINETEST_DEBUG:-1}
 
 # parse command-line options
-while [ "$#" != 0 ]; do
+while [ "$#" -gt 0 ]; do
     case "$1" in
     -h)
 	usage
@@ -59,6 +62,10 @@ while [ "$#" != 0 ]; do
     ;;
     -v)
 	WINETEST_DEBUG=`expr $WINETEST_DEBUG + 1`
+    ;;
+    -i)
+	WINETEST_INTERACTIVE=1
+	export WINETEST_INTERACTIVE
     ;;
     -s)
 	WINETEST_REPORT_SUCCESS=1
@@ -74,29 +81,43 @@ while [ "$#" != 0 ]; do
 	shift; topobjdir="$1"
 	if [ ! -d "$topobjdir" ]; then usage; fi
     ;;
-    --)
-	break
-    ;;
     *)
-	infile="$1"
+	break
     ;;
     esac
     shift
 done	    
 	
-# we must have found an input file
-if [ ! -f "$infile" ]; then usage; fi
-
-# set program to the .c file base name if not specified otherwise
 if [ -z "$program" ]; then
-    program=`basename "$infile" .c`
+    # try to autodetect the test program name based on the working directory
+    working_path=`pwd`
+    case $working_path in
+        */dlls/*/tests)
+          parent_path=`dirname "$working_path"`
+          program=`basename "$parent_path"`_test.exe.so
+          ;;
+        */dlls/*)
+          program=tests/`basename "$working_path"`_test.exe.so
+          ;;
+        */programs/*/tests)
+          parent_path=`dirname "$working_path"`
+          program=`basename "$parent_path"`.exe_test.exe.so
+          ;;
+        */programs/*)
+          program=tests/`basename "$working_path"`.exe_test.exe.so
+          ;;
+    esac
+fi
+if [ ! -f "$program" ]; then
+    echo "Can't find the test program, use the -p argument to specify one" 1>&2
+    usage
 fi
 
 # check/detect topobjdir
 if [ -n "$topobjdir" ]; then
     if [ ! -f "$topobjdir/server/wineserver" ]
     then
-	echo "Wrong -T argument, $topobjdir/server/wineserver does not exist" 2>&1
+	echo "Wrong -T argument, $topobjdir/server/wineserver does not exist" 1>&2
 	usage
     fi
 else
@@ -104,6 +125,9 @@ else
     elif [ -f "../server/wineserver" ]; then topobjdir=".."
     elif [ -f "../../server/wineserver" ]; then topobjdir="../.."
     elif [ -f "../../../server/wineserver" ]; then topobjdir="../../.."
+    else
+        echo "Can't find the top of the Wine tree (use the -T argument)" 1>&2
+        usage
     fi
 fi
 
@@ -116,4 +140,10 @@ fi
 WINETEST_PLATFORM=${platform:-wine}
 export WINETEST_PLATFORM WINETEST_DEBUG
 
-exec "$topobjdir/wine" "$program" "$infile" "$@"
+# WINETEST_WRAPPER is normally empty, but can be set by caller, e.g.
+#  WINETEST_WRAPPER=time
+# would give data about how long each test takes, and
+#  WINETEST_WRAPPER=valgrind
+# would run the tests under valgrind to look for memory errors.
+
+exec $WINETEST_WRAPPER "$topobjdir/wine" "$program" "$@"
diff --git a/tools/winewrapper b/tools/winewrapper
--- a/tools/winewrapper
+++ b/tools/winewrapper
@@ -16,16 +16,19 @@
 #
 # You should have received a copy of the GNU Lesser General Public
 # License along with this library; if not, write to the Free Software
-# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
+# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301, USA
 #
 
 # first determine the directory that contains the app itself
 
 appdir=""
+name=$0
+
 case "$0" in
   */*)
     # $0 contains a path, use it
     appdir=`dirname "$0"`
+    name=`basename "$0"`
     ;;
   *)
     # no directory in $0, search in PATH
@@ -34,7 +37,7 @@ case "$0" in
     for d in $PATH
     do
       IFS=$saved_ifs
-      if [ -x "$d/$0" ]
+      if [ -x "$d/$name" ]
       then
         appdir="$d"
         break
@@ -43,7 +46,7 @@ case "$0" in
     ;;
 esac
 
-# now find the top-level directory of the source tree
+# now find the top-level directory of the build tree
 
 if [ -x "$appdir/server/wineserver" ]
 then topdir="$appdir"
@@ -54,7 +57,7 @@ then topdir="$appdir/../.."
 elif [ -x "$appdir/../../../server/wineserver" ]
 then topdir="$appdir/../../.."
 else
-  echo "$0: could not locate Wine source tree"
+  echo "$name: could not locate the Wine build tree"
   exit 1
 fi
 
@@ -62,21 +65,36 @@ fi
 
 topdir=`cd "$topdir" && pwd`
 
-if [ -n "$LD_LIBRARY_PATH" ]
+if [ "`uname -s`" = "Darwin" ]
 then
-  LD_LIBRARY_PATH="$topdir/libs:$LD_LIBRARY_PATH"
+  if [ -n "$DYLD_LIBRARY_PATH" ]
+  then
+    DYLD_LIBRARY_PATH="$topdir/libs/wine:$DYLD_LIBRARY_PATH"
+  else
+    DYLD_LIBRARY_PATH="$topdir/libs/wine"
+  fi
+  export DYLD_LIBRARY_PATH
 else
-  LD_LIBRARY_PATH="$topdir/libs"
+  if [ -n "$LD_LIBRARY_PATH" ]
+  then
+    LD_LIBRARY_PATH="$topdir/libs/wine:$LD_LIBRARY_PATH"
+  else
+    LD_LIBRARY_PATH="$topdir/libs/wine"
+  fi
+  export LD_LIBRARY_PATH
 fi
-if [ -n "$WINEDLLPATH" ]
-then
-  WINEDLLPATH="$topdir/dlls:$topdir/programs:$WINEDLLPATH"
+
+if [ -x "$topdir/loader/$name" ]
+then WINELOADER="$topdir/loader/$name"
+elif [ -x "$topdir/loader/wine" ]
+then WINELOADER="$topdir/loader/wine"
+elif [ -x "$topdir/loader/wine64" ]
+then WINELOADER="$topdir/loader/wine64"
 else
-  WINEDLLPATH="$topdir/dlls:$topdir/programs"
+  echo "$name: could not find the Wine loader in $topdir"
+  exit 1
 fi
-WINESERVER="$topdir/server/wineserver"
-WINELOADER="$topdir/loader/wine"
-export LD_LIBRARY_PATH WINEDLLPATH WINESERVER WINELOADER
+export WINELOADER
 
 # any local settings ?
 if [ -f "$topdir/.winewrapper" ]
@@ -84,27 +102,6 @@ then
     . $topdir/.winewrapper
 fi
 
-# create prefix directory if needed
-
-if [ -z "$WINEPREFIX" -a ! -d "$HOME/.wine" ]
-then
-    "$topdir/tools/wineprefixcreate" --use-wine-tree "$topdir"
-fi
-
 # and run the application
 
-case "$0" in
-  wine|*/wine)
-    exec "$WINELOADER" "$@"
-    ;;
-  */*)
-    [ -f "$0.exe.so" ] && exec "$WINELOADER" "$0.exe.so" "$@"
-    echo "$0: cannot find corresponding application"
-    exit 1
-    ;;
-  *)
-    [ -f "$appdir/$0.exe.so" ] && exec "$WINELOADER" "$appdir/$0.exe.so" "$@"
-    echo "$0: cannot find corresponding application"
-    exit 1
-    ;;
-esac
+exec "$WINELOADER" "$@"
